source "https://rubygems.org"

gem "jekyll", ">=4.0.0"
gem "jekyll-watch", ">=2.0.0"
gem 'jekyll-autoprefixer', ">=1.0.0"
gem "jekyll-github-metadata"
gem "liquid", ">=4.0.0"
gem "pygments.rb", ">=1.2.1"
gem "redcarpet", ">=3.1"
gem "rake", ">=10.0.0"
gem "sassc",">=2.4.0"
gem "uglifier",">=4.1.0"
gem "nokogiri", ">= 1.10.4"
gem "activesupport", ">= 6.0.3.1"
